In [ ]:
#1d arrays in numpy and python lists
import numpy as np
#basic array creation
arr1 = np.array([1,2,3,4,5])
pylist=[1,2,3,4,5]
np.array(pylist)#coverting a python list to a numpy array
print(arr1)
print(pylist)



[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [11]:
#2d arrays 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#array generation functions
#-------------arange------------------
arr=np.arange(0,10)
arr2=np.arange(0,10,2)
print(arr)
print(arr2)
#-------------zeros------------------
zero_array=np.zeros(5)
zero_array2d=np.zeros((3,3))
print("1d zero array:")
print()
print(zero_array)
print()
print("2d zero array:")
print()
print(zero_array2d)
#-------------ones------------------
one_array1d=np.ones(5)
one_array2d=np.ones((3,3))
print("1d one array:")  
print()
print(one_array1d)  
print()
print("2d one array:")
print()     
print(one_array2d)
print()
#-------linspace------------------
lin_array=np.linspace(0,1,5)
print("linspace array:")
print()
print(lin_array)    

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
1d zero array:

[0. 0. 0. 0. 0.]

2d zero array:

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1d one array:

[1. 1. 1. 1. 1.]

2d one array:

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

linspace array:

[0.   0.25 0.5  0.75 1.  ]


In [25]:
#random generation functions
#-------------rand------------------
rand_array=np.random.rand(10)
print("Random array:")
print(rand_array)    
#-------------randn------------------
randn_array=np.random.randn(10) 
print("Random normal array:")
print(randn_array)   
#-------------randint------------------ 
randint_array=np.random.randint(0,10,5)
print("Random integer array:")  
print(randint_array)


Random array:
[0.14759699 0.39031666 0.20716222 0.93963392 0.61913621 0.08899758
 0.52540382 0.28054715 0.45708073 0.36935277]
Random normal array:
[ 0.6278735   0.76447232  0.50276319 -0.50114361 -0.75819846  0.54813925
  1.14743484  1.02549829  2.13692483  0.42588972]
Random integer array:
[5 4 2 7 6]


In [ ]:
#array attributes
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])                 
print("Array shape:",arr.shape)       #there are no brackets in attribute access                    
print("Array size:",arr.size)
print("Array data type:",arr.dtype) 


Array shape: (3, 3)
Array size: 9
Array data type: int64


In [26]:
#array methods
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:")        
print(arr)
print()
min_value=arr.min()
max_value=arr.max() 
print("Minimum value:",min_value)
print("Maximum value:",max_value)
sum_value=arr.sum()
print("Sum of all elements:",sum_value) 
sum_of_columns=arr.sum(axis=0)
print("Sum of columns:",sum_of_columns)
sum_of_rows=arr.sum(axis=1)
print("Sum of rows:",sum_of_rows)   
mean_value=arr.mean()
print("Mean value:",mean_value)
median_value=np.median(arr)
print("Median value:",median_value)
std_dev=np.std(arr)
print("Standard deviation:",std_dev)
            

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Minimum value: 1
Maximum value: 9
Sum of all elements: 45
Sum of columns: [12 15 18]
Sum of rows: [ 6 15 24]
Mean value: 5.0
Median value: 5.0
Standard deviation: 2.581988897471611


In [29]:
#reshaping and resizing in numpy
arr=np.arange(1,31)
arr_reshaped=arr.reshape(6,5)
print("Original array:")    
print(arr)
print()
print("Reshaped array:")
print(arr_reshaped)


Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

Reshaped array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
